Каталог по ПП
htmlacademy-htmlcss/1347475-nerds-29 pull request #11
Opened 2020-10-28 19:28 UTC by ddlein

2020-10-28 19:30 UTC, ddlein commented on css/style.css
> +.sort-list::before {
почему то при наведении на ссылку тип сортировки, также загорается стрелка

2020-10-28 19:33 UTC, ddlein commented on css/style.css
> +.catalog-item:nth-child(2) .modal-title {
тут иначе не знаю как выровнять элементы, учитывая что длина слова разная, может флекс задать...

2020-10-28 19:33 UTC, ddlein commented on css/style.css
> +.sort-list::before {
почему то при наведении на ссылку тип сортировки, также загорается стрелка

2020-10-29 07:51 UTC, PavelNyukalo requested changes

2020-10-29 07:51 UTC, PavelNyukalo commented on catalog.html
> +        <button class="show-choosen btn--grey">Показать</button>
А кнопке добавь `type="submit"`, и тогда форма будет отправляться по адресу, указанному в `action`. Так мы еще и доп. требования ТЗ выполним

2020-10-29 07:51 UTC, PavelNyukalo commented on css/style.css
> +  ;
Лишняя ;

2020-10-29 07:51 UTC, PavelNyukalo commented on css/style.css
> +.sort-list::before {
Это происходит потому что ниже у тебя стоит `.sort-list:hover::after`, то бишь при наведении на весь `sort-list`, у `::after` меняется `opacity`
Предлагаю кнопки сортировки добавить отдельными `button`, так удобнее будет их стилизовать, а также потом на них можно было бы повесить обработчики через JS (нам это не нужно в проекте). Можешь их в отдельный `ul` вынести

2020-10-29 07:51 UTC, PavelNyukalo commented on css/style.css
> +.catalog-item:nth-child(2) .modal-title {
Всю эту простыню ниже действительно нет смысла писать, элементов списка может быть намного больше, и прописывать для каждого свойства нет смысла. 
Как предлагаю сделать:
1. Убрать простыню до `.modal-button`
2. Задать `.modal` `box-sizing: border-box и padding: 26px 80px 80px 44px`
3. Задать `margin` например только `.modal-subtitle` и добиться таким образом ПП (отличия для разных модалок в 1-2px не критично, подгонять каждую нет смысла)

Если возникнут трудности можем созвониться, я тебе с демонстрацией покажу

2020-10-29 07:51 UTC, PavelNyukalo commented on css/style.css
>  }
Ты про этот костыль говорил? 
![image](https://user-images.githubusercontent.com/52506235/97538296-f98c7580-19e1-11eb-847d-c320719f3074.png)

Предлагаю немного разметку поменять, сделать ее так:
`main`
`h1.main-title` (оставляем как сейчас)
затем добавляем `section.products__container` например, ограничиваем его по ширине (1160), выравниваем по центру и делаем flex-контейнером, и в него уже вкладываем `form `и `div.products__wrapper` например.
В `div.products__wrapper` вкладываем `div` с сортировкой, список продуктов `ul` и пагинацию

И у нас получится что-то подобное, флексом можно по краям прибить
![image](https://user-images.githubusercontent.com/52506235/97539794-67d23780-19e4-11eb-9533-f76d71406698.png)

Опять же, если что, можем созвониться

2020-10-29 07:51 UTC, PavelNyukalo commented on css/style.css
>  }
А, и у `main` убрать `display: grid`, оставить по-умолчанию `block`

2020-10-29 14:49 UTC, ddlein commented on catalog.html
>        <form method="get" action="">
ок

2020-10-29 14:50 UTC, ddlein commented on catalog.html
> +        <button class="show-choosen btn--grey">Показать</button>
ok

2020-10-29 14:59 UTC, ddlein commented on css/style.css
> +  ;
ok

2020-10-30 19:23 UTC, ddlein commented on css/style.css
> +.catalog-item:nth-child(2) .modal-title {
ok

2020-10-30 19:23 UTC, ddlein commented on css/style.css
> +.sort-list::before {
ok

2020-10-30 19:23 UTC, ddlein commented on css/style.css
>  }
ok

2020-10-31 16:05 UTC, PavelNyukalo approved these changes

2020-10-31 16:06 UTC, merged