Создана разметка главной страницы и добавлена пустая страница каталога
htmlacademy-htmlcss/1347475-nerds-29 pull request #2
Opened 2020-09-26 19:45 UTC by ddlein

В написании текста путался в выборе тегов между h1-h6 и тега <p> и не уверен что все обозначил правильно

2020-09-27 12:54 UTC, ddlein commented on index.html
> -
Случайно оставил футер пустым изначально

2020-09-27 17:13 UTC, PavelNyukalo requested changes

2020-09-27 17:13 UTC, PavelNyukalo commented on index.html
> +        <img src="https://via.placeholder.com/160x65" alt="Логотип сайта Нердс">
Всем контентным изображениям необходимо задать атрибуты width и height, это критерий Д1

2020-09-27 17:13 UTC, PavelNyukalo commented on index.html
> +    <button>НАПИШИТЕ НАМ</button>
Само окошко с контактами можно обернуть в div, чтобы можно было задать фоновый цвет

2020-09-27 17:13 UTC, PavelNyukalo commented on index.html
> +    <p>Скидка 10% для друзей из социальных сетей.</p>
Этот раздел тоже лучше обернуть, например, в section, чтобы можно было легко позиционировать и задавать фоновый цвет

2020-09-27 17:13 UTC, PavelNyukalo commented on catalog.html
> +        <li><a href="catalog.html">Магазин</a></li>
Здесь думаю стоит убрать "catalog.html", чтобы ссылка не вела сама на себя

2020-09-27 18:59 UTC, ddlein commented on index.html
> +  <main>
ok

2020-09-27 18:59 UTC, ddlein commented on index.html
> +      <h2>Слайды приемуществ</h2>
ok

2020-09-27 19:00 UTC, ddlein commented on index.html
> +          <button>УЗНАТЬ БОЛЬШЕ</button>
ok

2020-09-27 19:03 UTC, ddlein commented on index.html
> +          <button>УЗНАТЬ БОЛЬШЕ</button>
ok

2020-09-27 19:03 UTC, ddlein commented on index.html
> +          <h4>ВЕБ-САЙТЫ</h4>
ok

2020-09-27 19:04 UTC, ddlein commented on index.html
> +      </h3>
ok

2020-09-27 19:06 UTC, ddlein commented on index.html
> +          </p>
ok

2020-09-27 19:06 UTC, ddlein commented on index.html
> +      <h4>ВЫПОЛНЯЕМ ЗАКАЗЫ НА РАЗРАБОТКУ:</h4>
ok

2020-09-27 19:07 UTC, ddlein commented on index.html
> +      </a>
ok

2020-09-27 19:09 UTC, ddlein commented on index.html
> +          <button>ЗАКАЗАТЬ</button>
ok

2020-09-27 19:10 UTC, ddlein commented on index.html
> +    <button>НАПИШИТЕ НАМ</button>
Исправил, но к сожалению JS не знаю и пока не представляю как это сделать

2020-09-27 19:13 UTC, ddlein commented on index.html
> +    <img src="https://via.placeholder.com/231x190" alt="Точка местоположения дома">
Я сперва так и подумал, но потом в макете увидел что маркер и карта это 2 разных изображения и решил сделать 2 тега img
![map 1](https://user-images.githubusercontent.com/70834132/94373544-ae472480-010e-11eb-81dd-db582cd9be55.png)
![map-marker 1](https://user-images.githubusercontent.com/70834132/94373545-aedfbb00-010e-11eb-98c0-3b57234513e4.png)

2020-09-27 19:16 UTC, ddlein commented on index.html
> +        <img src="https://via.placeholder.com/160x65" alt="Логотип сайта Нердс">
Сделаю

2020-09-27 19:16 UTC, ddlein commented on index.html
> +    <button>НАПИШИТЕ НАМ</button>
ok

2020-09-27 19:17 UTC, ddlein commented on index.html
> +    <p>Скидка 10% для друзей из социальных сетей.</p>
ok

2020-09-27 19:18 UTC, ddlein commented on catalog.html
> +        <li><a href="catalog.html">Магазин</a></li>
ok

2020-09-27 19:48 UTC, ddlein commented on index.html
> +          <img src="https://via.placeholder.com/760x431" alt="Разметка приложения на айфоне">
ок
фоновая картинка будет через CSS ведь?

2020-09-28 13:58 UTC, PavelNyukalo requested changes

2020-09-28 13:58 UTC, PavelNyukalo commented on catalog.html
> +        </li>
Ссылкой по техническому заданию является только название, а не полностью карточка (https://up.htmlacademy.ru/htmlcss/29/project/nerds#nerds-3-10).
И в самой карточке нужно еще разметить всплывающий при наведении блок описания
![Screenshot_1](https://user-images.githubusercontent.com/52506235/94440627-51ee0e80-01bb-11eb-890e-0a7cfbefa3ce.png)

2020-09-29 04:57 UTC, PavelNyukalo approved these changes

2020-09-29 05:00 UTC, merged